version: '3.8'

services:
  go:
    build:
      context: .
      dockerfile: go/Dockerfile
      target: ${ENV_MODE:-development}
    container_name: go
    ports:
      - "8080:8080"
    volumes:
      - ./go:/app
    working_dir: /app
    environment:
      ENV_MODE: ${ENV_MODE:-development}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

  react:
    build:
      context: .
      dockerfile: react/Dockerfile
      target: ${ENV_MODE:-development}
    container_name: react
    ports:
      - "5173:5173"
    volumes:
      - ./react/vite-project:/app
    working_dir: /app
    environment:
      - NODE_ENV=${ENV_MODE:-development}
    networks:
      - app-network
    stdin_open: true
    tty: true

  mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
