version: '3.8'

services:
  go:
    container_name: go
    restart: always
    build:
      context: ./go
    volumes:
      - ./go:/usr/src/app
      # - ./locales:/usr/src/locales
    environment:
      TZ: ${TZ}
      URL_DEVELOP: ${URL_DEVELOP}
      URL_PROD: ${URL_PROD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      NODE_ENV: ${ENV_MODE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    expose:
      - "8080"
    tty: true
    stdin_open: true
    depends_on:
      - mysql
    networks:
      - default

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
    volumes:
      - ./etc/nginx/:/etc/nginx/
      - ./var/log/nginx/:/var/log/nginx/
      - ./react/project/dist:/usr/share/nginx/html
      - ./etc/logrotate.d/:/etc/logrotate.d/
      - ./var/www/html:/var/www/html
    environment:
      TZ: ${TZ}
      NODE_ENV: ${ENV_MODE}
      AWS_MODE: "true"
    ports:
      - "80:80"
    tty: true
    stdin_open: true
    entrypoint: ["/bin/sh", "-c", "cron && /etc/nginx/generate_nginx_conf.sh && nginx -g 'daemon off;'"]
    depends_on:
      - go
    networks:
      - default

  mysql:
    container_name: mysql
    restart: always
    build:
      context: ./mysql
    volumes:
      - ./var/lib/mysql/:/var/lib/mysql/
      - ./mysql/backup:/backup
      - ./etc/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      TZ: ${TZ}
      NODE_ENV: ${ENV_MODE}
    expose:
      - "3306"
    tty: true
    stdin_open: true
    networks:
      - default

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.112.0/24